//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMT_v1 {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ABMT_v1.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ADB Error:.
        /// </summary>
        internal static string AdbError {
            get {
                return ResourceManager.GetString("AdbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Archiving:.
        /// </summary>
        internal static string Archiving {
            get {
                return ResourceManager.GetString("Archiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Return to main menu (9).
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1. Backup.
        /// </summary>
        internal static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The number of files in Android/data/:.
        /// </summary>
        internal static string BackupMedia_Android_data_Count {
            get {
                return ResourceManager.GetString("BackupMedia.Android/data Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3. Audio.
        /// </summary>
        internal static string BackupMedia_Audio {
            get {
                return ResourceManager.GetString("BackupMedia.Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I&apos;m creating a backup archive..
        /// </summary>
        internal static string BackupMedia_BackupArchive {
            get {
                return ResourceManager.GetString("BackupMedia.BackupArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The backup has been successfully created:.
        /// </summary>
        internal static string BackupMedia_BackupCreated {
            get {
                return ResourceManager.GetString("BackupMedia.BackupCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на conventional.
        /// </summary>
        internal static string BackupMedia_Conventional {
            get {
                return ResourceManager.GetString("BackupMedia.Conventional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на copied.
        /// </summary>
        internal static string BackupMedia_Copied {
            get {
                return ResourceManager.GetString("BackupMedia.Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error when copying a file:.
        /// </summary>
        internal static string BackupMedia_CopyError {
            get {
                return ResourceManager.GetString("BackupMedia.CopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4. Documents.
        /// </summary>
        internal static string BackupMedia_Documents {
            get {
                return ResourceManager.GetString("BackupMedia.Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the numbers of the file types, separated by a space, that you want to save (e.g. 1 2 for photos and videos):.
        /// </summary>
        internal static string BackupMedia_EnterNumb {
            get {
                return ResourceManager.GetString("BackupMedia.EnterNumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hidden.
        /// </summary>
        internal static string BackupMedia_Hidden {
            get {
                return ResourceManager.GetString("BackupMedia.Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на in Android/data/.
        /// </summary>
        internal static string BackupMedia_In_android_data {
            get {
                return ResourceManager.GetString("BackupMedia.In android/data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect selection. Backup canceled..
        /// </summary>
        internal static string BackupMedia_IncorrectSelect {
            get {
                return ResourceManager.GetString("BackupMedia.IncorrectSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1. Photo.
        /// </summary>
        internal static string BackupMedia_Photo {
            get {
                return ResourceManager.GetString("BackupMedia.Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type &apos;D&apos; to include files from android/data/ in the backup..
        /// </summary>
        internal static string BackupMedia_PressD {
            get {
                return ResourceManager.GetString("BackupMedia.PressD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type &apos;H&apos; to include hidden files in the backup..
        /// </summary>
        internal static string BackupMedia_PressH {
            get {
                return ResourceManager.GetString("BackupMedia.PressH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Backup Size:.
        /// </summary>
        internal static string BackupMedia_Size {
            get {
                return ResourceManager.GetString("BackupMedia.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Backup Startup....
        /// </summary>
        internal static string BackupMedia_Start {
            get {
                return ResourceManager.GetString("BackupMedia.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total number of files:.
        /// </summary>
        internal static string BackupMedia_TotalFiles {
            get {
                return ResourceManager.GetString("BackupMedia.TotalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The total size of the files found:.
        /// </summary>
        internal static string BackupMedia_TotalFileSize {
            get {
                return ResourceManager.GetString("BackupMedia.TotalFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2. Video.
        /// </summary>
        internal static string BackupMedia_Video {
            get {
                return ResourceManager.GetString("BackupMedia.Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Backup.
        /// </summary>
        internal static string BackupMenu {
            get {
                return ResourceManager.GetString("BackupMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect your device..
        /// </summary>
        internal static string ConnectDevice {
            get {
                return ResourceManager.GetString("ConnectDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connected Device:.
        /// </summary>
        internal static string ConnectedDevice {
            get {
                return ResourceManager.GetString("ConnectedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The current status of the connection:.
        /// </summary>
        internal static string ConnectionStatus_State {
            get {
                return ResourceManager.GetString("ConnectionStatus.State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No connected device.
        /// </summary>
        internal static string ConnectionStatus_status {
            get {
                return ResourceManager.GetString("ConnectionStatus.status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connected via USB.
        /// </summary>
        internal static string ConnectionStatus_USB {
            get {
                return ResourceManager.GetString("ConnectionStatus.USB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connected via Wi-Fi.
        /// </summary>
        internal static string ConnectionStatus_Wifi {
            get {
                return ResourceManager.GetString("ConnectionStatus.Wifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The device is connected via Wi-Fi..
        /// </summary>
        internal static string ConnectToDeviceOverWifi_Connected {
            get {
                return ResourceManager.GetString("ConnectToDeviceOverWifi.Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wi-Fi connection error..
        /// </summary>
        internal static string ConnectToDeviceOverWifi_ConnectERROR {
            get {
                return ResourceManager.GetString("ConnectToDeviceOverWifi.ConnectERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The IP address cannot be blank..
        /// </summary>
        internal static string ConnectToDeviceOverWifi_EmptyIP {
            get {
                return ResourceManager.GetString("ConnectToDeviceOverWifi.EmptyIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the Wi-fi network connection code: .
        /// </summary>
        internal static string ConnectToDeviceOverWifi_EnterCODE {
            get {
                return ResourceManager.GetString("ConnectToDeviceOverWifi.EnterCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the IP address of the device (e.g. 192.168.1.2): .
        /// </summary>
        internal static string ConnectToDeviceOverWifi_EnterIP {
            get {
                return ResourceManager.GetString("ConnectToDeviceOverWifi.EnterIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the port: .
        /// </summary>
        internal static string ConnectToDeviceOverWifi_EnterPORT {
            get {
                return ResourceManager.GetString("ConnectToDeviceOverWifi.EnterPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press any key to return to the main menu..
        /// </summary>
        internal static string ConnectToDeviceOverWifi_PressAnyKey {
            get {
                return ResourceManager.GetString("ConnectToDeviceOverWifi.PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To connect via Wi-Fi you need to turn it on and go to (Debug via Wi-Fi -&gt; Connect device with connection code) and enter the data from there.
        /// </summary>
        internal static string ConnectToDeviceOverWifi_StartMSG {
            get {
                return ResourceManager.GetString("ConnectToDeviceOverWifi.StartMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copying:.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0. Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Files.
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Backup folder not found..
        /// </summary>
        internal static string FolderNotFind {
            get {
                return ResourceManager.GetString("FolderNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect selection. Press any key to reselect..
        /// </summary>
        internal static string IncorrectSelection {
            get {
                return ResourceManager.GetString("IncorrectSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are no available backups to restore..
        /// </summary>
        internal static string NoAvailableBackups {
            get {
                return ResourceManager.GetString("NoAvailableBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Or type &apos;C&apos; to continue without the device..
        /// </summary>
        internal static string PressC {
            get {
                return ResourceManager.GetString("PressC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2. Restore from Backup.
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на restored..
        /// </summary>
        internal static string Restored {
            get {
                return ResourceManager.GetString("Restored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error while restoring a file:.
        /// </summary>
        internal static string RestoreMedia_ErrorRestoring {
            get {
                return ResourceManager.GetString("RestoreMedia.ErrorRestoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File not found or not selected..
        /// </summary>
        internal static string RestoreMedia_FileNotSelected {
            get {
                return ResourceManager.GetString("RestoreMedia.FileNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect selection. Restore canceled..
        /// </summary>
        internal static string RestoreMedia_IncorrectSelection {
            get {
                return ResourceManager.GetString("RestoreMedia.IncorrectSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Metadata file could not be found. Restoration is not possible..
        /// </summary>
        internal static string RestoreMedia_MetadataNotFind {
            get {
                return ResourceManager.GetString("RestoreMedia.MetadataNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error reading the metadata file..
        /// </summary>
        internal static string RestoreMedia_ReadingError {
            get {
                return ResourceManager.GetString("RestoreMedia.ReadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restoration is complete..
        /// </summary>
        internal static string RestoreMedia_RestoreDone {
            get {
                return ResourceManager.GetString("RestoreMedia.RestoreDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select the file to restore:.
        /// </summary>
        internal static string RestoreMedia_SelectRestoreFile {
            get {
                return ResourceManager.GetString("RestoreMedia.SelectRestoreFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the numbers of the file types, separated by a space, that you want to recover (for example, 1 2 for photos and videos):.
        /// </summary>
        internal static string RestoreMedia_SelectRestoreFiles {
            get {
                return ResourceManager.GetString("RestoreMedia.SelectRestoreFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restore from backup.
        /// </summary>
        internal static string RestoreMenu {
            get {
                return ResourceManager.GetString("RestoreMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select an action:.
        /// </summary>
        internal static string SelectAction {
            get {
                return ResourceManager.GetString("SelectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the file number of the file to be recovered: .
        /// </summary>
        internal static string SelectFileNumb {
            get {
                return ResourceManager.GetString("SelectFileNumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Start backup (1).
        /// </summary>
        internal static string StartBackup {
            get {
                return ResourceManager.GetString("StartBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Restore from backup (1).
        /// </summary>
        internal static string StartRestore {
            get {
                return ResourceManager.GetString("StartRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3. Connect via Wi-Fi.
        /// </summary>
        internal static string WI_Fi_Connect {
            get {
                return ResourceManager.GetString("WI-Fi Connect", resourceCulture);
            }
        }
    }
}
